apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: intake-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: intake-service
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: repo-fetcher-scaler
spec:
  scaleTargetRef:
    name: repo-fetcher-service
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: rabbitmq
      metadata:
        queueName: repo_fetcher_queue
        mode: QueueLength
        value: '5'
        hostFromEnv: RABBITMQ_URL
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: vibe-review-scaler
spec:
  scaleTargetRef:
    name: vibe-review-service
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: rabbitmq
      metadata:
        queueName: vibe_review_queue
        mode: QueueLength
        value: '5'
        hostFromEnv: RABBITMQ_URL
